#!/usr/bin/env bash
source _setup

mkdir -p ./.export

# 将模型切片, 默认输出gcode数据
#$app --slice ./.export/Toothy_Baby_Croc.obj --output ./.export

# 等效 --slice
#$app --export-gcode ./.export/Toothy_Baby_Croc.obj --output ./.export/Toothy_Baby_Croc_2.gcode

# 在指定的z轴位置切割模型, (未测通)
#$app --slice ./.export/Toothy_Baby_Croc.obj --cut 0.6 --output ./.export/Toothy_Baby_Croc_cut1.gcode

# 使用指定配置进行切片
$app --slice ./model/Toothy_Baby_Croc.stl --output ./.export --load ./superslicer/slice_config.ini \
  --nozzle-diameter 0.1 --layer-height 0.1 --scale-to-fit 20,20,20 --center 0,0